const assert=require('node:assert/strict');
const C=require('../config.js'), Game=require('../engine.js');
let n=0;function check(name,fn){fn();console.log('PASS',name);n++}
function clean(){const g=new Game(C,()=>0);g.start();g.nextSpawn=Infinity;return g}
function book(g,t,lane=0){g.books.push({lane,row:3,next:t,step:650,id:t})}
check('four discrete rows and fixed per-book tempo',()=>{const g=new Game(C,()=>0);g.start();g.advance(600);assert.equal(g.books[0].row,0);g.advance(1249);assert.equal(g.books[0].row,0);g.advance(1250);assert.equal(g.books[0].row,1);g.advance(1900);assert.equal(g.books[0].row,2);assert.equal(g.books[0].step,650)});
check('instant movement and capacity 0 through 5; overflow misses',()=>{const g=clean();g.move(0);assert.equal(g.lane,0);for(let i=1;i<=6;i++){book(g,i);g.advance(i);assert.equal(g.load,Math.min(i,5))}assert.equal(g.missed,1);assert.equal(g.score,0)});
check('shelving duration is 200 ms per book for all loads',()=>{for(let count=1;count<=5;count++){const g=clean();g.load=count;assert(g.shelve());assert.equal(g.shelving.end,count*200);g.advance(count*200-1);assert(g.shelving);g.advance(count*200);assert.equal(g.score,count);assert.equal(g.load,0);assert.equal(g.shelving,null)}});
check('one book leaves cart and scores at each completed cycle',()=>{const g=clean();g.load=5;g.shelve();for(let count=1;count<=5;count++){g.advance(count*200-1);assert.equal(g.score,count-1);assert.equal(g.load,6-count);g.advance(count*200);assert.equal(g.score,count);assert.equal(g.load,5-count)}});
check('lane 4, input lock, falling continues, no duplicate shelving',()=>{const g=clean();g.load=3;g.shelve();assert.equal(g.lane,3);g.move(0);assert.equal(g.lane,3);assert(!g.shelve());book(g,500,3);g.advance(599);assert.equal(g.score,2);assert.equal(g.missed,1);g.advance(600);assert.equal(g.score,3);assert.equal(g.load,0);assert.equal(g.lane,3);assert(!g.shelve());g.move(0);assert.equal(g.lane,0)});
check('deadline counts completed books only, excludes exact tie',()=>{const g=clean();g.time=29500;g.load=5;g.shelve();g.advance(30000);assert.equal(g.score,2);assert.equal(g.load,3);assert.equal(g.state,'lost');const tie=clean();tie.time=29800;tie.load=1;tie.shelve();tie.advance(30000);assert.equal(tie.score,0)});
check('goal exceeded keeps playing, 30/15 allowed, success only at 30 s',()=>{const g=clean();g.score=14;g.load=5;g.shelve();g.advance(1000);assert.equal(g.state,'playing');assert.equal(g.score,19);g.load=5;g.shelve();g.advance(2000);g.load=5;g.shelve();g.advance(3000);g.load=1;g.shelve();g.advance(3200);assert.equal(g.score,30);assert.equal(g.state,'playing');g.advance(29999);assert.equal(g.state,'playing');g.advance(30000);assert.equal(g.state,'won');assert.equal(g.time,30000)});
check('restart resets time, scores, books, last sprite and input lock',()=>{const g=clean();g.score=30;g.load=4;g.shelve();g.advance(30000);g.start();assert.equal(g.score,0);assert.equal(g.load,0);assert.equal(g.shelving,null);assert.equal(g.lastDrop,null);assert.equal(g.books.length,0);assert.equal(g.time,0);assert.equal(g.state,'playing')});
check('frame-rate independent simulation including multi-book shelving',()=>{const a=new Game(C,()=>.5),b=new Game(C,()=>.5);a.start();b.start();a.move(2);b.move(2);a.advance(6000);for(let t=17;t<6000;t+=17)b.advance(t);b.advance(6000);a.shelve();b.shelve();a.advance(20000);for(let t=6017;t<20000;t+=17)b.advance(t);b.advance(20000);assert.equal(JSON.stringify(a),JSON.stringify(b))});
check('smooth decreasing spawn and fall intervals',()=>{const g=new Game(C,()=>0);g.start();g.advance(0);const first=g.drops[0].step;g.advance(1200);assert(g.drops[0].step<first);assert(g.nextSpawn-1200<1200)});
check('floor limit and expiration',()=>{const g=clean();for(let i=1;i<=20;i++){book(g,i);g.advance(i)}assert.equal(g.floor.length,C.floorLimit);g.advance(3000);assert.equal(g.floor.length,0)});

check('stop spawning at 29 s and drain every existing book',()=>{const g=new Game(C,()=>.75);g.start();g.advance(C.spawnUntil);const count=g.serial;assert(g.lastDrop.start<C.spawnUntil);assert.equal(g.nextSpawn,Infinity);assert(g.lastLandingAt>C.duration);g.advance(g.lastLandingAt+0.001);assert.equal(g.serial,count);assert.equal(g.books.length,0);assert.equal(g.drops.length,0);assert.equal(g.state,'playing');assert(Math.abs(g.finishAt-g.lastLandingAt-C.cleanupGrace)<.001)});
check('last book can be caught and reshelved during the 2 s grace',()=>{const g=new Game({...C,target:1},()=>.75);g.start();g.advance(C.spawnUntil);g.load=0;g.move(3);g.advance(g.lastLandingAt+0.001);assert(g.load>0);const lastLoad=g.load;assert(g.shelve());g.advance(g.time+lastLoad*C.shelvePerBook);assert.equal(g.score,lastLoad);assert.equal(g.load,0);assert.equal(g.state,'playing');g.advance(g.finishAt-.001);assert.equal(g.state,'playing');g.advance(g.finishAt);assert.equal(g.state,'won');assert(g.time>C.duration)});
check('no new book starts exactly at the spawn cutoff',()=>{const g=new Game({...C,spawnUntil:1200},()=>0);g.start();g.advance(2000);assert.equal(g.serial,1);assert.equal(g.nextSpawn,Infinity)});
check('large frame gaps and small frames yield same extended result',()=>{const a=new Game(C,()=>.75),b=new Game(C,()=>.75);a.start();b.start();a.advance(100000);for(let t=17;t<40000;t+=17)b.advance(t);assert.equal(JSON.stringify(a),JSON.stringify(b));assert(a.time>C.duration);assert.equal(a.books.length,0)});


function perfectRun(){const g=new Game(C,()=>.75);g.start();let steps=0;while(g.state==='playing'){assert(++steps<1000);const next=Math.min(g.nextSpawn,g.shelving?.next??Infinity,...g.drops.map(d=>d.release),...g.books.map(b=>b.next),g.finishAt);g.advance(next);if(g.load&&!g.shelving&&g.state==='playing')g.shelve();}return g;}
check('perfect requires every generated book to be caught and reshelved',()=>{const g=perfectRun();assert.equal(g.state,'won');assert(g.serial>=C.target);assert.equal(g.caught,g.serial);assert.equal(g.score,g.serial);assert.equal(g.missed,0);assert.equal(g.isPerfect,true)});
check('a normal clear with a missed book is not perfect',()=>{const g=perfectRun();g.missed=1;g.score--;g.caught--;assert(g.score>=C.target);assert.equal(g.isPerfect,false)});
check('caught but unreshelved books prevent perfect',()=>{const g=perfectRun();g.score--;g.load=1;assert.equal(g.isPerfect,false)});
check('perfect cannot be awarded before the final result or after restart',()=>{const g=perfectRun();g.state='playing';assert.equal(g.isPerfect,false);g.state='won';assert.equal(g.isPerfect,true);g.start();assert.equal(g.isPerfect,false)});
check('an empty game cannot be perfect',()=>{const g=new Game({...C,target:0,spawnUntil:0});g.start();g.advance(C.duration);assert.equal(g.state,'won');assert.equal(g.isPerfect,false)});

console.log(n+' tests passed');
